type CurrencyInfo = {
  currency: string;
  code: string;
  symbol: string;
};
export const currencyData: Record<string, CurrencyInfo> = {
  AF: { currency: "Afghan Afghani", code: "AFN", symbol: "؋" },
  AL: { currency: "Albanian Lek", code: "ALL", symbol: "L" },
  DZ: { currency: "Algerian Dinar", code: "DZD", symbol: "دج" },
  AO: { currency: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
  AR: { currency: "Argentine Peso", code: "ARS", symbol: "$" },
  AM: { currency: "Armenian Dram", code: "AMD", symbol: "֏" },
  AU: { currency: "Australian Dollar", code: "AUD", symbol: "$" },
  AT: { currency: "Euro", code: "EUR", symbol: "€" },
  AZ: { currency: "Azerbaijani Manat", code: "AZN", symbol: "₼" },
  BS: { currency: "Bahamian Dollar", code: "BSD", symbol: "$" },
  BH: { currency: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
  BD: { currency: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
  BB: { currency: "Barbadian Dollar", code: "BBD", symbol: "$" },
  BY: { currency: "Belarusian Ruble", code: "BYN", symbol: "Br" },
  BE: { currency: "Euro", code: "EUR", symbol: "€" },
  BZ: { currency: "Belize Dollar", code: "BZD", symbol: "$" },
  BJ: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  BT: { currency: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
  BO: { currency: "Bolivian Boliviano", code: "BOB", symbol: "Bs." },
  BA: {
    currency: "Bosnia and Herzegovina Convertible Mark",
    code: "BAM",
    symbol: "KM",
  },
  BW: { currency: "Botswana Pula", code: "BWP", symbol: "P" },
  BR: { currency: "Brazilian Real", code: "BRL", symbol: "R$" },
  BN: { currency: "Brunei Dollar", code: "BND", symbol: "$" },
  BG: { currency: "Bulgarian Lev", code: "BGN", symbol: "лв" },
  BF: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  BI: { currency: "Burundian Franc", code: "BIF", symbol: "Fr" },
  KH: { currency: "Cambodian Riel", code: "KHR", symbol: "៛" },
  CM: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  CA: { currency: "Canadian Dollar", code: "CAD", symbol: "$" },
  CV: { currency: "Cape Verdean Escudo", code: "CVE", symbol: "$" },
  CF: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  TD: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  CL: { currency: "Chilean Peso", code: "CLP", symbol: "$" },
  CN: { currency: "Chinese Yuan", code: "CNY", symbol: "¥" },
  CO: { currency: "Colombian Peso", code: "COP", symbol: "$" },
  KM: { currency: "Comorian Franc", code: "KMF", symbol: "Fr" },
  CG: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  CD: { currency: "Congolese Franc", code: "CDF", symbol: "Fr" },
  CR: { currency: "Costa Rican Colón", code: "CRC", symbol: "₡" },
  HR: { currency: "Euro", code: "EUR", symbol: "€" },
  CU: { currency: "Cuban Peso", code: "CUP", symbol: "$" },
  CY: { currency: "Euro", code: "EUR", symbol: "€" },
  CZ: { currency: "Czech Koruna", code: "CZK", symbol: "Kč" },
  DK: { currency: "Danish Krone", code: "DKK", symbol: "kr" },
  DJ: { currency: "Djiboutian Franc", code: "DJF", symbol: "Fr" },
  DO: { currency: "Dominican Peso", code: "DOP", symbol: "RD$" },
  EG: { currency: "Egyptian Pound", code: "EGP", symbol: "£" },
  SV: { currency: "United States Dollar", code: "USD", symbol: "$" },
  GQ: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  ER: { currency: "Eritrean Nakfa", code: "ERN", symbol: "Nfk" },
  EE: { currency: "Euro", code: "EUR", symbol: "€" },
  SZ: { currency: "Swazi Lilangeni", code: "SZL", symbol: "E" },
  ET: { currency: "Ethiopian Birr", code: "ETB", symbol: "Br" },
  FI: { currency: "Euro", code: "EUR", symbol: "€" },
  FR: { currency: "Euro", code: "EUR", symbol: "€" },

  GA: {
    currency: "Central African CFA Franc",
    code: "XAF",
    symbol: "Fr",
  },
  GM: { currency: "Gambian Dalasi", code: "GMD", symbol: "D" },
  GE: { currency: "Georgian Lari", code: "GEL", symbol: "₾" },
  DE: { currency: "Euro", code: "EUR", symbol: "€" },
  GH: { currency: "Ghanaian Cedi", code: "GHS", symbol: "₵" },
  GR: { currency: "Euro", code: "EUR", symbol: "€" },
  GT: { currency: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
  GN: { currency: "Guinean Franc", code: "GNF", symbol: "Fr" },
  GW: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  GY: { currency: "Guyanese Dollar", code: "GYD", symbol: "$" },
  HT: { currency: "Haitian Gourde", code: "HTG", symbol: "G" },
  HN: { currency: "Honduran Lempira", code: "HNL", symbol: "L" },
  HU: { currency: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  IS: { currency: "Icelandic Króna", code: "ISK", symbol: "kr" },
  IN: { currency: "Indian Rupee", code: "INR", symbol: "₹" },
  ID: { currency: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  IR: { currency: "Iranian Rial", code: "IRR", symbol: "﷼" },
  IQ: { currency: "Iraqi Dinar", code: "IQD", symbol: "ع.د" },
  IE: { currency: "Euro", code: "EUR", symbol: "€" },
  IL: { currency: "Israeli New Shekel", code: "ILS", symbol: "₪" },
  IT: { currency: "Euro", code: "EUR", symbol: "€" },
  JM: { currency: "Jamaican Dollar", code: "JMD", symbol: "$" },
  JP: { currency: "Japanese Yen", code: "JPY", symbol: "¥" },
  JO: { currency: "Jordanian Dinar", code: "JOD", symbol: "د.ا" },
  KZ: { currency: "Kazakhstani Tenge", code: "KZT", symbol: "₸" },
  KE: { currency: "Kenyan Shilling", code: "KES", symbol: "Sh" },
  KI: { currency: "Australian Dollar", code: "AUD", symbol: "$" },
  KW: { currency: "Kuwaiti Dinar", code: "KWD", symbol: "د.ك" },
  KG: { currency: "Kyrgyzstani Som", code: "KGS", symbol: "с" },
  LA: { currency: "Lao Kip", code: "LAK", symbol: "₭" },
  LV: { currency: "Euro", code: "EUR", symbol: "€" },
  LB: { currency: "Lebanese Pound", code: "LBP", symbol: "ل.ل" },
  LS: { currency: "Lesotho Loti", code: "LSL", symbol: "L" },
  LR: { currency: "Liberian Dollar", code: "LRD", symbol: "$" },
  LY: { currency: "Libyan Dinar", code: "LYD", symbol: "ل.د" },
  LI: { currency: "Swiss Franc", code: "CHF", symbol: "Fr" },
  LT: { currency: "Euro", code: "EUR", symbol: "€" },
  LU: { currency: "Euro", code: "EUR", symbol: "€" },

  MG: { currency: "Malagasy Ariary", code: "MGA", symbol: "Ar" },
  MW: { currency: "Malawian Kwacha", code: "MWK", symbol: "MK" },
  MY: { currency: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  MV: { currency: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf" },
  ML: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  MT: { currency: "Euro", code: "EUR", symbol: "€" },
  MR: { currency: "Mauritanian Ouguiya", code: "MRU", symbol: "UM" },
  MU: { currency: "Mauritian Rupee", code: "MUR", symbol: "₨" },
  MX: { currency: "Mexican Peso", code: "MXN", symbol: "$" },
  MD: { currency: "Moldovan Leu", code: "MDL", symbol: "L" },
  MC: { currency: "Euro", code: "EUR", symbol: "€" },
  MN: { currency: "Mongolian Tögrög", code: "MNT", symbol: "₮" },
  ME: { currency: "Euro", code: "EUR", symbol: "€" },
  MA: { currency: "Moroccan Dirham", code: "MAD", symbol: "د.م." },
  MZ: { currency: "Mozambican Metical", code: "MZN", symbol: "MT" },
  MM: { currency: "Burmese Kyat", code: "MMK", symbol: "Ks" },
  NA: { currency: "Namibian Dollar", code: "NAD", symbol: "$" },
  NP: { currency: "Nepalese Rupee", code: "NPR", symbol: "₨" },
  NL: { currency: "Euro", code: "EUR", symbol: "€" },
  NZ: { currency: "New Zealand Dollar", code: "NZD", symbol: "$" },
  NI: { currency: "Nicaraguan Córdoba", code: "NIO", symbol: "C$" },
  NE: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  NG: { currency: "Nigerian Naira", code: "NGN", symbol: "₦" },
  MK: { currency: "Macedonian Denar", code: "MKD", symbol: "ден" },
  NO: { currency: "Norwegian Krone", code: "NOK", symbol: "kr" },
  OM: { currency: "Omani Rial", code: "OMR", symbol: "ر.ع." },
  PK: { currency: "Pakistani Rupee", code: "PKR", symbol: "₨" },
  PA: { currency: "United States Dollar", code: "USD", symbol: "$" },
  PG: { currency: "Papua New Guinean Kina", code: "PGK", symbol: "K" },
  PY: { currency: "Paraguayan Guaraní", code: "PYG", symbol: "₲" },
  PE: { currency: "Peruvian Sol", code: "PEN", symbol: "S/." },
  PH: { currency: "Philippine Peso", code: "PHP", symbol: "₱" },
  PL: { currency: "Polish Złoty", code: "PLN", symbol: "zł" },
  PT: { currency: "Euro", code: "EUR", symbol: "€" },
  QA: { currency: "Qatari Riyal", code: "QAR", symbol: "ر.ق" },
  RO: { currency: "Romanian Leu", code: "RON", symbol: "lei" },
  RU: { currency: "Russian Ruble", code: "RUB", symbol: "₽" },
  RW: { currency: "Rwandan Franc", code: "RWF", symbol: "Fr" },

  WS: { currency: "Samoan Tālā", code: "WST", symbol: "T" },
  ST: {
    currency: "São Tomé and Príncipe Dobra",
    code: "STN",
    symbol: "Db",
  },
  SA: { currency: "Saudi Riyal", code: "SAR", symbol: "ر.س" },
  SN: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  RS: { currency: "Serbian Dinar", code: "RSD", symbol: "дин." },
  SC: { currency: "Seychellois Rupee", code: "SCR", symbol: "₨" },
  SL: { currency: "Sierra Leonean Leone", code: "SLE", symbol: "Le" },
  SG: { currency: "Singapore Dollar", code: "SGD", symbol: "$" },
  SK: { currency: "Euro", code: "EUR", symbol: "€" },
  SI: { currency: "Euro", code: "EUR", symbol: "€" },
  SB: { currency: "Solomon Islands Dollar", code: "SBD", symbol: "$" },
  SO: { currency: "Somali Shilling", code: "SOS", symbol: "Sh" },
  ZA: { currency: "South African Rand", code: "ZAR", symbol: "R" },
  KR: { currency: "South Korean Won", code: "KRW", symbol: "₩" },
  SS: { currency: "South Sudanese Pound", code: "SSP", symbol: "£" },
  ES: { currency: "Euro", code: "EUR", symbol: "€" },
  LK: { currency: "Sri Lankan Rupee", code: "LKR", symbol: "₨" },
  SD: { currency: "Sudanese Pound", code: "SDG", symbol: "ج.س." },
  SR: { currency: "Surinamese Dollar", code: "SRD", symbol: "$" },
  SE: { currency: "Swedish Krona", code: "SEK", symbol: "kr" },
  CH: { currency: "Swiss Franc", code: "CHF", symbol: "Fr" },
  SY: { currency: "Syrian Pound", code: "SYP", symbol: "£" },
  TW: { currency: "New Taiwan Dollar", code: "TWD", symbol: "NT$" },
  TJ: { currency: "Tajikistani Somoni", code: "TJS", symbol: "ЅМ" },
  TZ: { currency: "Tanzanian Shilling", code: "TZS", symbol: "Sh" },
  TH: { currency: "Thai Baht", code: "THB", symbol: "฿" },
  TL: { currency: "United States Dollar", code: "USD", symbol: "$" },
  TG: { currency: "West African CFA Franc", code: "XOF", symbol: "Fr" },
  TO: { currency: "Tongan Paʻanga", code: "TOP", symbol: "T$" },
  TT: {
    currency: "Trinidad and Tobago Dollar",
    code: "TTD",
    symbol: "TT$",
  },
  TN: { currency: "Tunisian Dinar", code: "TND", symbol: "د.ت" },
  TR: { currency: "Turkish Lira", code: "TRY", symbol: "₺" },
  TM: { currency: "Turkmenistani Manat", code: "TMT", symbol: "m" },
  UG: { currency: "Ugandan Shilling", code: "UGX", symbol: "Sh" },
  UA: { currency: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
  AE: {
    currency: "United Arab Emirates Dirham",
    code: "AED",
    symbol: "د.إ",
  },
  GB: { currency: "Pound Sterling", code: "GBP", symbol: "£" },
  US: { currency: "United States Dollar", code: "USD", symbol: "$" },
  UY: { currency: "Uruguayan Peso", code: "UYU", symbol: "$" },
  UZ: { currency: "Uzbekistani Soʻm", code: "UZS", symbol: "so'm" },
  VU: { currency: "Vanuatu Vatu", code: "VUV", symbol: "Vt" },
  VE: {
    currency: "Venezuelan Bolívar Soberano",
    code: "VES",
    symbol: "Bs.",
  },
  VN: { currency: "Vietnamese Đồng", code: "VND", symbol: "₫" },
  YE: { currency: "Yemeni Rial", code: "YER", symbol: "﷼" },
  ZM: { currency: "Zambian Kwacha", code: "ZMW", symbol: "ZK" },
  ZW: { currency: "Zimbabwean Dollar", code: "ZWL", symbol: "$" },
};
